policies:
  any:
    any:
      any: "ignore"
  cloud-resources-public-access:
    critical:
      high: "block"
      medium: "block"
      low: "block"
      not_set: "block"
    warning:
      high: "block"
      medium: "block"
      low: "block"
      not_set: "block"
    minor:
      medium: "ignore"
      high: "ignore"
      low: "ignore"
      not_set: "ignore"
disabled_rules: {}
